---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: {{ .Chart.Version }}
    name: nextensio
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
    template:
      metadata:
        labels:
          app: {{ template "fullname" . }}
          chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
          version: 1.0.0
      spec:
        containers:
        - image: "{{ .Values.nextensio.image.name }}:{{ .Values.nextensio.image.tag }}"
          imagePullPolicy: {{ .Values.nextensio.image.pullPolicy }}
          name: nextensio
        env:
          - name: EXTENDER_KEY
            value: "{{ .Values.nextensio.image.key }}"
