---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      version: {{ .Chart.Version }}
    name: nextensio
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
    template:
      metadata:
        labels:
          app: {{ template "fullname" . }}
          chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      spec:
        containers:
        - image: "{{ .Values.nextensio.image.name }}:{{ .Values.nextensio.image.tag }}"
          imagePullPolicy: {{ .Values.nextensio.image.pullPolicy }}
          name: nextensio
          env:
            - name: EXTENDER_KEY
              value: "{{ .Values.nextensio.image.key }}"
            - name: GATEWAY_NAME
              value: "gatewaylnnj1.nextensio.net"
