apiVersion: v1
name: microservice1
description: Web Frontend for video processing
version: 1.0.10
appVersion: "1.0.10"
keywords:
  - microservice1
  - nextensio
  - platform9
home: https://github.com/nextensio/helm-charts/demos_platform9_microservice1
maintainers:
- name: nextensio
  email: support@nextensio.com
