---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      version: {{ .Chart.Version }}
    name: microservice2
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
    template:
      metadata:
        labels:
          app: {{ template "fullname" . }}
          chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      spec:
        containers:
        - image: "{{ .Values.microservice2.image.name }}:{{ .Values.microservice2.image.tag }}"
          imagePullPolicy: {{ .Values.microservice2.image.pullPolicy }}
          name: microservice2
