---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    name: db-service
  spec:
    type: NodePort
    selector:
      app: {{ template "fullname" . }}
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 27017
