kubernetes:
  host: https://kubernetes.default

nextensio:
  namespace: default
  image:
    name: gopakumarce/extender
    tag: latest
    pullPolicy: Always
    key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnQiOiJlbmVseCIsInN1YiI6ImdpbGxldGVhenVyZUBlbmVseC5jb20iLCJzZWNyZXQiOiJza2I0WXBSR1oxOXIzL3ZVQzVmemokdCNObC13S3lBWChuTHh1e1BpIVFlY2QwRldWNjhnfjdTT0lEYEorMmFIIn0.3OW7sDqY20QCmKD8pCi-Ijf0a3L_-hxOX3AjnZot7V8
