apiVersion: v1
name: MicroService3
description: AI engine for video processing
version: 1.0.3
keywords:
  - microService3
  - nextensio
  - platform9
home: https://github.com/nextensio/helm-charts/demos_platform9_microService3
maintainers:
- name: Nextensio
  email: support@nextensio.com
